### ISSUE TITLE
Key already exists

### ISSUE THREAD

**Issue by aledefra** [multiversx/mx-delegation-dapp#17]
When adding a node, because of this check:
https://github.com/multiversx/mx-delegation-dapp/blob/76e4ae0cb2936e5edb7d6e41be6480396ec040f9/src/components/Nodes/components/Dropzone/Dropzone.tsx#L124
You get an error about the node already existing, even if the node was just started as an observer and was not staked.
I don't know if this is an intended behavior, but I think it would be better to check if the node is actually already staked, or it is just started and connected to the network

**Comment by schimih** [comment]
Hey @aledefra 
on it. Thanks for noticing it. :+1:
